/*
TODO : vérifier ordre pour la création
*/

DROP TABLE IF EXISTS UTILISATEURS;
CREATE TABLE UTILISATEURS(
	id 				INT 			NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	login 			VARCHAR(100) 	NOT NULL,
	password 		VARCHAR(255) 	NOT NULL
);

DROP TABLE IF EXISTS RECETTES;
CREATE TABLE RECETTES(
	id 				INT				NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	nom 			VARCHAR(100) 	NOT NULL,
	utilisateur_id	INT				NOT NULL	REFERENCES UTILISATEURS(id)
);

DROP TABLE IF EXISTS UNITES;
CREATE TABLE UNITES(
	id 				INT 			NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	nom 			VARCHAR(100)	NOT NULL
);

DROP TABLE IF EXISTS AGENDAS;
CREATE TABLE AGENDAS(
	id 				INT 			NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	nom 			VARCHAR(100) 	NOT NULL 	DEFAULT 'Agenda'
);

DROP TABLE IF EXISTS MENUS;
CREATE TABLE MENUS(
	id 				INT				NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	jour 			DATE			NOT NULL,
	agenda_id		INT				NOT NULL	REFERENCES AGENDA(id)
);

DROP TABLE IF EXISTS PRODUITS;
CREATE TABLE PRODUITS(
	id 				INT				NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	nom				VARCHAR(100) 	NOT NULL,
	unite_id		INT				NOT NULL 	REFERENCES UNITES(id)
);

DROP TABLE IF EXISTS BESOINS;
CREATE TABLE BESOINS(
	id 				INT 			NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
	produit_id 		INT				NOT NULL	REFERENCES PRODUITS(id),
	recette_id 		INT				NOT NULL	REFERENCES RECETTES(id),
	quantite		INT				NOT NULL	DEFAULT 0
);